name: "Destroy terraform"
on:
  workflow_dispatch:
    
permissions: read-all
jobs:
  terraform:
    name: "Terraform"
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      - name: SSH Private key
        run: echo '${{ secrets.PRIVATE_KEY }}' >> "id_ed25519"

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve